name: Create Template Branch

on:
  push:
    branches:
      - main

jobs:
  create-template-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create template branch
        run: |
          git checkout main
          git branch -D template || true
          git checkout -b template
          git rm -rf --cached --ignore-unmatch "_posts" "Gemfile.lock"
          git commit -m "Update template branch"
          git push origin template -f

